#!/bin/zsh

gemkill ./files ./ "http://www.milofultz.com"

new_changes=$(git status | grep -i "modified")

if [[ ! -z "$new_changes" ]]
then
    git add .
    git commit -m "Update `date +'%Y-%m-%d %H:%M:%S'`"
    git push origin HEAD
fi

